### ISSUE TITLE
Epic 144: Card "Ціни" - Fix Translations

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#146]
- [x] Task 146: "Duration" -> "Тривалість"
 - [x] Task 146: "Price" -> "Ціна"
 - [x] Task 146: "hours:minute" -> "години:хвилини"
