### ISSUE TITLE
[epic 161]: EN to UA Localization

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#162]
- [x] [task #162]: The Label on the Button "Menu" Change to "Меню"
 - [x] [task #162]: The Hint "Write text" in the Search Input Change to "Пошук"
 - [x] [task #162]: For English the Hint "Write text" in the Search Input Change to "Search"
 - [x] [task #162]: Column Name "Повнe Імʼя" to "Назва"
 - [x] [task #162]: Column Name "Активний" to "Активна"
 - [x] [task #162]: Value "active" of the Column Active to "Активна"
 - [x] [task #162]: For English the Value "active" Change to "Active"
 - [x] [task #162]: Value "Inactive" of the Column Active to "Неактивна"
 - [x] [task #162]: Table Info - "Total" Change to "Всього"
 - [x] [task #162]: Table Info - "Last update: N seconds" Change to "Останнє оновлення: N сек."
 - [x] [task #162]: Label of the Cache Refresh Button - "Оновити кеш"
