### ISSUE TITLE
[epic 169]: EN to UA Localization

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#171]
- [x] [task 171]: "Attendees" -> "Учасники"
 - [x] [task 171]: "Booking Start" -> "Заплановано на"
 - [x] [task 171]: "Estimated End" -> "Планується завершити"
