### ISSUE TITLE
[epic 174]: Choose Service Pop-up

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#177]
Follow [the Figma design](https://www.figma.com/proto/mPGEP9RHCTjYpESzHF40WA/Landing?type=design&node-id=729-3592&t=wHSpXPIAxdzPyvL5-1&scaling=scale-down&page-id=0%3A1&starting-point-node-id=302%3A10203&show-proto-sidebar=1&mode=design) to build the service pop-up:

 - [x] [task 177]: Add Title "Choose Services"
 - [x] [task 177]: Build a Template for Selecting Service Item
 - [x] [task 177]: Display a List of the Created Services
