### ISSUE TITLE
[epic 198]: Collect All Main Info into Details Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#202]
- [x] [task 202]: Title "Details:" (UA -> "Опис:")
 - [x] [task 202]: Status Badge "requested" (UA -> "запит")
 - [x] [task 202]: Subtitle "Clients:" (UA -> "Клієнти:")
 - [x] [task 202]: List of Clients, where Client Item: Index, Full Name, Email, Phone Number 
 - [x] [task 202]: Subtitle "Service:" (UA -> "Клієнти:")
 - [x] [task 202]: Service Info the Same as in Epic #194 
 - [x] [task 202]: Subtitle "Date and time:" (UA -> "Дата і час:")
 - [x] [task 202]: Date-time Value in Format: << Weekday, DD Month Name, YYYY at HH:MM >>
 - [x] [task 202]: Subtitle "Note:" (UA -> "Нотатка:")
 - [x] [task 202]: Note Text
