### ISSUE TITLE
[epic 198]: Add Action Buttons underneath the Details Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#204]
- [x] [task 204]: Add Cancel Button
 - [x] [task 204]: Cancel Function: Change Status of the Event to "Cancelled" + Refreshes the Page
 - [x] [task 204]: Add Edit Button
 - [x] [task 204]: Edit Function: Open Event Edit Page for the Current Event
 - [x] [task 204]: Add Approve Button
 - [x] [task 204]: Approve Function: Change Status of the Event to "Booked" + Refresh the Page
 - [x] [task 204]: EN -> UA: "Cancel" -> "Скасувати"
 - [x] [task 204]: EN -> UA: "Cancelled" -> "Скасована"
 - [x] [task 204]: EN -> UA: "Edit" -> "Редагувати"
 - [x] [task 204]: EN -> UA: "Approve" -> "Прийняти"
