### ISSUE TITLE
Collect the Main Data into Details Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#215]
- [x] Card Title is the Full Name of the Client
 - [x] Subtitle "Email:" (in UA "Електронна скринька:")
 - [x] Client's Email Address
 - [x] Subtitle "Phone:" (in UA "Номер телефону:")
 - [x] Client's Phone Number
 - [x] Subtitle "Note:" (in UA "Примітка:")
 - [x] Note of the Client
