### ISSUE TITLE
Event Details Page: Simplify Details Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#221]
- [x] Instead Title "Details" Use Service Name
 - [x] Remove Another Service Name to the Right of the Service Picture
 - [x] Use Whole Freed Space for Service Description Text
