### ISSUE TITLE
Create Logo Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#223]
- [x] Card Title "Logo" (in UA "Логотип")
 - [x] Logo Preview Field (Use FlowBite [Dropzone](https://flowbite.com/docs/forms/file-input/#dropzone))
 - [x] Preview Field Hint Line 1: "**Click to upload**" in (in UA "**Натисніть для завантаження**")
 - [x] Preview Field Hint Line 2: "or drag and drop" in (in UA "або перетягніть")
 - [x] Text 1 to the Right: "You can inject a little more personality into your business profile and help people recognize you by uploading a logo (an image, photo or other graphic icon of "you")."
 - [x] UA Translation of Text 1: "Ти можеш надати своєму бізнес-профілю трохи більше особистості і допомогти людям тебе розпізнати, завантаживши логотип (зображення, фото чи іншу графічну піктограму, що тебе представляє)"
 - [x] Text 2 to the Right: "Allowed types: SVG, PNG, JPG or GIF (MAX. 256x256px)"
 - [x] UA Translation of Text 2: "Дозволені типи файлів: SVG, PNG, JPG або GIF (MАКС. 256x256пікс)"
