### ISSUE TITLE
Create Cover Image Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#224]
- [x] Card Title "Cover image" (in UA "Банер")
 - [x] Cover Image Preview Field (Use FlowBite [Dropzone](https://flowbite.com/docs/forms/file-input/#dropzone))
 - [x] Leave the Icon from the FlowBite Dropzone
 - [x] Hint Text Line 1: "**Click to upload** or drag and drop" (in UA "**Натисніть для завантаження** або перетягніть")
 - [x] Hint Text Line 2: "SVG, PNG, JPG or GIF (MAX. 2400x1000px)" (in UA "SVG, PNG, JPG або GIF (MАКС. 2400x1000пікс)")
