### ISSUE TITLE
Create Profile Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#225]
- [x] Card Title "Profile" (in UA "Профіль")
 - [ ] Add Activity Toggle Button to the Right of the Title
 - [ ] Add Public Activation Toggle Buttons to Each of the Fields
 - [x] Field Label "Business name" (in UA "Назва бізнесу")
 - [x] Field Text Input with a Hint "Your business name" (in UA "Назва твоєї компанії")
 - [x] Field Label "Business description" (in UA "Опис компанії")
 - [x] Field Text Input with a Hint "Shortly describe what you do" (in UA "Коротко опиши свій бізнес")
 - [x] Field Label "Business category" (in UA "Бізнес категорія")
 - [x] Field Selection Input with List of Possible Categories: "Beauty salon", "Barbershop", "Hairdresser", "Online Consultation", "Online Teaching", "Dentistry" (in UA "Салон краси", "Барбершоп", "Перукарня", "Онлайн консультація", "Онлайн навчання", "Стоматологія")
 - [x] Field Label "Feature" (in UA "Особливість")
 - [x] Field Text Input with a Hint "Enter catching phrase" (in UA "Коротка фраза, що зацікавить потенційного клієнта")
