### ISSUE TITLE
Create Gallery Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#229]
- [x] Card Title "Gallery" (in UA "Галерея")
 - [x] #233
 - [x] If There Are Less Then 6 Images: Add One More [FlowBite Dropzone](https://flowbite.com/docs/forms/file-input/#dropzone) to Upload New Image 
 - [x] Add Hint Text "Upload images that demonstrate your work from the best side. Images must be 1800px wide by 900px high and in JPEG or PNG format. You may upload up to 6 images"
 - [x] UA Translation of the Hint "Завантажуй зображення, що демонструють твою роботу з найкращого боку. Зображення 1800 на 900 пікселів підходять найкраще для даного портфоліо, підтримувані формати JPEG та PNG. Ти можеш завантажити до 6 зображень."
