### ISSUE TITLE
Create Facilities Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#230]
- [x] Card Title "Facilities" (in UA "Зручності")
 - [x] 1. Check Box Field with Label "Internet (Wi-Fi)" (in UA "Інтернет (Wi-Fi)")
 - [x] 1. Field Icon: [bi-wifi](https://icons.getbootstrap.com/icons/wifi/)
 - [x] 2. Check Box Field with Label "Accepting credit cards" (in UA "Приймаємо оплату карткою")
 - [x] 2. Field Icon: [bi-credit-card-2-front](https://icons.getbootstrap.com/icons/credit-card-2-front/)
 - [x] 3. Check Box Field with Label "Accommodations for people with disabilities" (in UA "Умови для людей з фізичними обмеженнями")
 - [x] 3. Field Icon: [icon-wheelchair](https://www.figma.com/proto/mPGEP9RHCTjYpESzHF40WA/Landing?type=design&node-id=850-3815&t=gS3pttuhCo9KH89K-1&scaling=contain&page-id=1%3A2&starting-point-node-id=499%3A12505&mode=design)
 - [x] 4. Check Box Field with Label "Child-friendly" (in UA "Пристосовано для дітей")
 - [x] 4. Field Icon: [icon-child-friendly](https://www.figma.com/proto/mPGEP9RHCTjYpESzHF40WA/Landing?type=design&node-id=850-3819&t=7CGss2iUSBRbqPCe-1&scaling=contain&page-id=1%3A2&starting-point-node-id=499%3A12505&mode=design)
 - [x] 5. Check Box Field with Label "Pet allowed" (in UA "Можна з домашніми улюбленцями")
 - [x] 5. Field Icon: [icon-paw](https://www.figma.com/proto/mPGEP9RHCTjYpESzHF40WA/Landing?type=design&node-id=850-3832&t=eLbxNxAQLpcqfw4B-1&scaling=contain&page-id=1%3A2&starting-point-node-id=499%3A12505&mode=design)
 - [x] 6. Check Box Field with Label "Free parking" (in UA "Безкоштовне паркування")
 - [x] 6. Field Icon: [bi-p-circle](https://icons.getbootstrap.com/icons/p-circle/)
