### ISSUE TITLE
Create Address Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#245]
- [x] Card Title "Address" (in UA "Адреса")
 - [ ] Add Public Activation Toggle Buttons to Each of the Fields
 - [x] Label "Country" (in UA "Країна")
 - [ ] Selection Input with List of Possible Countries
 - [x] Label "City" (in UA "Населений пункт")
 - [ ] Selection Input with List of Possible Settlements
 - [x] Label "Zip-code" (in UA "Індекс")
 - [x] Text Input with Zip-code with Hint "Your zip-code" (in UA "Твій індекс")
 - [x] Label "Address Line 1" (in UA "Адреса 1")
 - [x] Text Input with a Hint "Street, avn., boulevard, etc. name" (in UA "Назва вулиці, алеї чи бульвару")
 - [x] Label "Address Line 2" (in UA "Адреса 2")
 - [x] Text Input with a Hint "Office, house, etc. number" (in UA "Номер будинку, офісу або студії")
