### ISSUE TITLE
Create Booking Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#246]
- [x] Card Title "Cover image" (in UA "Банер")
 
 - [x] Label "When an event can be booked" (in UA "Коли можна зарезервувати послугу")
 
- [x] Hint Text underneath the Label "Set of period of rolling weeks people can book in your calendar" (in UA ""Встанови період тижнів з плаваючим графіком, які люди можуть бронювати в твоєму календарі")
 
- [x] Select Input Field of the Time Durations: 
 1. "This week and next week" (in UA "Цей і наступний тиждень") - Default
 2. "3 Weeks" (in UA "3 тижні")
 3. "4 Weeks" (in UA "4 тижні")
 4. "5 Weeks" (in UA "5 тижнів")
 5. "6 Weeks" (in UA "6 тижнів")
 6. "7 Weeks" (in UA "7 тижнів")
 7. "8 Weeks" (in UA "8 тижнів")
 8. "No limits" (in UA "Без обмежень")
 
- [x] Label "Minimum notice time" (in UA "Мінімальний час сповіщення")
 
- [x] Hint Text underneath the Label "Minimum amount of time before a service can be booked" (in Ukrainian "Мінімальний час перед можливістю забронювати послугу")
 
- [x] Select Input Field of the Time Durations: 
 1.  No minimal notice time (in UA "Без мінімального часу сповіщення")
 2. "15 minutes" (in UA "15 хвилин")
 3. "30 minutes" (in UA "30 хвилин")
 9. "1 hour" (in UA "1 година")
 10. "2 hours" (in UA "2 години")
 11. "3 hours" (in UA "3 години")
 12. "4 hours" (in UA "4 години")
 13. "5 hours" (in UA "5 годин")
 14. "6 hours" (in UA "6 годин")
 15. "1 day" (in UA "1 день") - Default
 16. "3 days" (in UA "3 дні")
 17. "7 days" (in UA "7 днів")

- [x] Label "Approval time" (in UA "Час на підтвердження")
 
- [x] Hint Text underneath the Label "Time after which the requested event will be canceled, if not approved" (in Ukrainian "Час, після якого незатверджена подія буде скасована")
 
- [x] Select Input Field of the Time Durations: 
 1. "5 minutes" (in UA "5 хвилин")
 3. "10 minutes" (in UA "10 хвилин")
 4. "15 minutes" (in UA "15 хвилин")
 5. "20 minutes" (in UA "20 хвилин")
 6. "30 minutes" (in UA "30 хвилин")
 7. "45 minutes" (in UA "45 хвилин")
 8. "1 hour" (in UA "1 година") - Default
 9. "2 hours" (in UA "2 години")
 10. "3 hours" (in UA "3 години")
 11. "4 hours" (in UA "4 години")
 18. "5 hours" (in UA "5 годин")
 19. "6 hours" (in UA "6 годин")
 20. "7 hours" (in UA "7 годин")
 21. "8 hours" (in UA "8 годин")
 22. "1 day" (in UA "1 день")
