### ISSUE TITLE
Rebuild General Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#248]
- [x] Add the Title of the Card "General" (in UA "Загальне")
  - [x] Label "Theme" (in UA "Тема")
  - [x] Select Field with Choices: "Light", "Dark", "Auto (theme of your system)" (choices in UA: "Темна", "Світла" та "Автоматично (тема твоєї операційної системи)") 
  - [x] Label "Language" (in UA "Мови")
  - [x] Select Field with Choices: "English", "Українська" та "Polski"
