### ISSUE TITLE
Rebuild Events Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#249]
- [x] Card Title "Events" (in UA "Події")
 - [x] Replace All Fields with a Placeholder Text "Coming soon..." (in UA "Невдовзі з'явиться...")
 - [x] Field Label "Default event language" (in UA "Мова події по-замовчуванню")
 - [x] Field Label "Default event service (top service)" (in UA "Попередньо визначена послуга (перша у списку)")
