### ISSUE TITLE
Rebuild Services Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#250]
- [x] Card Title "Services" (in UA "Послуги")
 - [x] Replace All Fields with a Placeholder Text "Coming soon..." (in UA "Невдовзі з'явиться...")
 - [x] Field Label "Default service duration" (in UA "Тривалість послуги по-замовчуванню")
 - [x] Field Label "Default service language" (in UA "Мова послуги по-замовчуванню")
 - [x] Field Label "Default service price" (in UA "Превстановлена ціна послуги")
