### ISSUE TITLE
Rebuild Danger Zone Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#251]
- [x] Title of the Card "Danger Zone"
 - [x] Hint Text: "Delete business account. After deleting the business account, there is no going back. Please consider this action carefully."
 - [x] UA Translation of the Hint Text: "Видалити бізнес-аккаунт. Після цього відновлення буде неможливим. Будь ласка, ретельно обдумай цей крок."
 - [x] Rebuild Deletion Button
 - [x] Deletion Button Text "Delete business account" (in UA "Видалити бізнес-аккаунт")
 - [x] Add a 1px Border to this Card, Color: bi-danger #E63756
