### ISSUE TITLE
Create Account Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#253]
- [x] Card Title "Account" (in "Профіль")
- [x] Add Edit Buttons to Each of the Fields (No Action for the Buttons for Now)
- [x] Label "Name:" (in UA "Повне імʼя:")
- [x] Label of the Full Name of the Business Client if Applied
- [x] If Full Name is not Applied, Use Placeholder "Your full name" (in UA "Твоє повне імʼя")
- [x] Label "Email:" (in UA "Електронна скринька:")
- [x] Label of the Email of the Business Client if Applied
- [ ] If Email is not Applied, Use Placeholder "your.email@example.com" (in UA "Твоя електронна скринька")
- [x] Label "Phone:" (in UA "Номер телефону:")
- [x] Label of the Phone Number of the Business Client if Applied
- [x] If Phone Number is not Applied, Use Placeholder "Your phone number" (in UA "Твій номер телефону")
- [ ] Label "Password:" (in UA "Пароль:")
- [ ] Label of 6 stars <<******>> and don't Care How the Actual Password Looks Like
