### ISSUE TITLE
Fix Delete Buttons for Uploaded Images on the Gallery Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#257]
- [x] Use [bi-trash3](https://icons.getbootstrap.com/icons/trash3/) for delete icon
 - [x] Remove white background of the icon
 - [x] Move the button more to the corner
