### ISSUE TITLE
Fix Working Hours Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#258]
- [x] The first working hours should be pre-set
 - [x] All next working hours on adding appear without any selection of weekdays
 - [x] Do not allow delete the working hours if there is only one working hours form component
 - [x] Move the delete button up, as shown on the example 1, example is shown below
 - [x] Stylize the add button as add buttons on previous forms (example 2, example is shown below)
 
Example 1:
<img width="758" alt="image" src="https://github.com/beeoclock/client-panel-app/assets/45332459/ef1f3cd5-8e38-4fed-86f7-94d39e16a829">
 
Example 2:
<img width="768" alt="image" src="https://github.com/beeoclock/client-panel-app/assets/45332459/b102431e-a6b3-4ff7-bedc-b102fadf8e5b">
