### ISSUE TITLE
Fix Social Media Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#259]
- [x] Do not show the input error: "Required field" (example 1, example is shown below)
 - [x] Do not change outline colour of the input field on focus out if the field is not filled
 - [x] Stylize the add button as add buttons on previous forms (example 2, example is shown below)

Example 1:
<img width="825" alt="image" src="https://github.com/beeoclock/client-panel-app/assets/45332459/9b9f6d0a-2401-4e7f-9d4d-91a07f254b74">

Example 2:
![image](https://github.com/beeoclock/client-panel-app/assets/45332459/d6be2dd7-4bd2-43df-af82-6a34eac5db63)
