### ISSUE TITLE
Fix Facilities Card

### ISSUE THREAD

**Issue by OleksiiDovhaniuk** [beeoclock/client-panel-app#260]
- [ ] Use default [Flowbite checkboxes](https://flowbite.com/docs/forms/checkbox/)  
 - [ ] Use bee-paw for Pets allowed field
 - [ ] Change colour of the icons and labels according to state of the field as in [Figma facility card](https://www.figma.com/proto/mPGEP9RHCTjYpESzHF40WA/Landing?type=design&node-id=1077-12549&t=uSa2jg50QM5Hrnnr-1&scaling=min-zoom&page-id=1%3A3&starting-point-node-id=1%3A2240&mode=design)

**Comment by CyJanek-00** [comment]
closed
