### ISSUE TITLE
Implement Expense Module on Panel

### ISSUE THREAD

**Issue by dokerwin** [beeoclock/client-panel-app#529]
### **Title**: Implement Expense Module on the Client-Panel

**Description**:
We need to implement a new tab on the panel to manage the **Expense Module** on the admin interface. The tab should allow users to view, create, update, and delete expenses, as well as manage expense categories.

### **Endpoints to Support**:

The following endpoints are already implemented in the backend and need to be adopted into the panel:

- **GET** `/api/v1/expense/paged`  
  - Fetch a paginated list of expenses.
  - **Optional Filters**:
    - **Date Range**: Fetch expenses within a specific date range (e.g., from `start` to `end`).
    - **Categories**: Fetch expenses by specific categories (e.g., Salary, Rent, Product Purchase).
  - This endpoint supports pagination and can be used to retrieve a subset of expenses filtered by the given criteria.

- **GET** `/api/v1/expense/{id}`  
  - Fetch a specific expense by its ID.
  
- **POST** `/api/v1/expense`  
  - Create a new expense.
  
- **PUT** `/api/v1/expense/{id}`  
  - Update an existing expense by its ID.
  
- **DELETE** `/api/v1/expense/{id}`  
  - Delete an expense by its ID.
  
- **GET** `/api/v1/expense/categories`  
  - Fetch all expense categories.
  
- **POST** `/api/v1/expense/categories`  
  - Add new expense categories.

Check with https://api.dev.beeoclock.com/panel/documentation/swagger/v1#/

Here’s the complete structure of the **Expense Module** with an interface that details each property along with descriptions, including how expenses and their related entities like categories, items, and sources should be structured.

You can add this section under the **Description** in the GitHub issue to give a clear overview of the expense structure.

---

### **Expense Structure as Interface with Description**

```typescript
export interface ExpenseDto {
  /**
   * Object identifier for the DTO (optional)
   */
  object?: 'ExpenseDto';

  /**
   * Unique identifier for the expense.
   */
  _id: string;

  /**
   * Total value of the expense, represented by the amount and the currency.
   */
  totalValue: ExpenseValueDto;

  /**
   * Date and time the expense was incurred. ISO
   */
  expensedAt: string;

  /**
   * Optional description providing more details about the expense.
   */
  description?: string;

  /**
   * Array of line items that represent the individual products, services, or salaries associated with the expense.
   */
  items?: ExpenseItemDto[];

  /**
   * Date and time when the expense was created (optional).
   */
  createdAt?: string;

  /**
   * Date and time when the expense was last updated (optional).
   */
  updatedAt?: string;
}

/**
 * Interface to represent the value of an expense.
 */
export interface ExpenseValueDto {
  /**
   * Object identifier for the DTO (optional)
   */
  object?: 'ExpenseValueDto';

  /**
   * Amount for the expense value.
   */
  amount: number;

  /**
   * Currency code (e.g., USD, EUR) representing the currency of the expense.
   */
  currency: CurrencyCodeEnum;
}

/**
 * Interface to represent individual line items within an expense.
 */
export interface ExpenseItemDto {
  /**
   * Object identifier for the DTO (optional)
   */
  object?: 'ExpenseLineItemDto';

  /**
   * Array of categories or tags to classify the expense (e.g., Salary, Rent, etc.)
   */
  categories: ExpenseCategoryDto[];

  /**
   * Total price for the line item (calculated as quantity * unit price if applicable).
   */
  itemValue: ExpenseValueDto;

  /**
   * Optional description to provide additional details about the line item.
   */
  description?: string;

  /**
   * The associated product, resource, or employee tied to this line item.
   */
  source: ExpenseSourceDto;
}

/**
 * Interface for representing an expense category or tag.
 */
export interface ExpenseCategoryDto {
  /**
   * Object identifier for the DTO (optional)
   */
  object?: 'ExpenseCategoryDto';

  /**
   * Name of the category (e.g., Salary, Rent, Product Purchase).
   */
  name: string;

  /**
   * Optional description providing more details about the category.
   */
  description?: string;
}

/**
 * Interface representing the source of an expense (e.g., a product, employee, or resource).
 */
export interface ExpenseSourceDto {
  /**
   * Object identifier for the DTO (optional)
   */
  object?: 'ExpenseSourceDto';

  /**
   * Unique ID of the source (e.g., product ID, employee ID).
   */
  sourceId: string;

  /**
   * Type of the source entity (e.g., Member, Product, Resource).
   */
  sourceType: ExpenseSourceTypeEnum;

  /**
   * Optional name of the source entity (e.g., the employee's name or product's name).
   */
  name?: string;

  /**
   * Optional description of the source.
   */
  description?: string;
}
```

### **Interface Breakdown**:

1. **`ExpenseDto`**: 
   - Represents the overall expense object.
   - Contains fields such as the total value, date of the expense (`expensedAt`), and optional description.
   - Can hold multiple items in the `items` array, where each item represents a product, service, or salary.

2. **`ExpenseValueDto`**:
   - Defines the value of an expense or a line item in terms of amount and currency.
   - The `amount` field is a number, and `currency` is a string enum (e.g., USD, EUR).

3. **`ExpenseItemDto`**:
   - Represents a single item in the expense.
   - Includes the associated categories, the item’s value, description, and a source that ties the line item to a product, resource, or member.

4. **`ExpenseCategoryDto`**:
   - Defines a category (tag) for the expense such as "Salary," "Rent," or "Utilities."
   - The category has a name and an optional description for further clarification.

5. **`ExpenseSourceDto`**:
   - Represents the source entity tied to the expense.
   - It could be a **Member** (e.g., an employee), a **Product**, or another type of resource.
   - The source is identified by its `sourceId` and `sourceType`.

### **New Business Preset**:

When a new business is onboarded, it should automatically be preconfigured with the following default expense categories:

```json
[
    {
        "name": "Salary",
        "description": "Expenses related to staff salaries and wages"
    },
    {
        "name": "Advance",
        "description": "Expenses related to staff advance"
    },
    {
        "name": "ProductPurchase",
        "description": "Purchases of beauty and barber supplies like shampoos, conditioners, and tools"
    },
    {
        "name": "Utilities",
        "description": "Expenses for electricity, water, gas, and internet"
    },
    {
        "name": "Rent",
        "description": "Monthly rental payments for the salon space"
    },
    {
        "name": "Equipment",
        "description": "Purchases or maintenance of equipment like clippers, scissors, and chairs"
    },
    {
        "name": "Marketing",
        "description": "Advertising and marketing expenses such as social media ads and flyers"
    },
    {
        "name": "Training",
        "description": "Costs for employee training and professional development"
    },
    {
        "name": "Cleaning",
        "description": "Cleaning supplies and services to maintain the salon"
    },
    {
        "name": "Insurance",
        "description": "Business insurance and liability coverage"
    },
    {
        "name": "Subscriptions",
        "description": "Software and service subscriptions like booking systems or management tools"
    },
    {
        "name": "Licenses",
        "description": "Fees for business licenses and permits"
    },
    {
        "name": "Delivery",
        "description": "Expenses related to product deliveries"
    },
    {
        "name": "Other",
        "description": "Miscellaneous expenses not covered by other categories"
    }
]
```

### **Expected Features**:

1. **Expense Management**:
   - A panel should be created to allow users to view, create, update, and delete expenses using the provided endpoints.
   - Expenses should have attributes like total value, line items, descriptions, and categories, as defined in the backend structure.

2. **Expense Categories**:
   - The panel should support listing, creating, and deleting expense categories using the provided `/categories` endpoints.
   - New businesses should automatically be preconfigured with the default expense categories listed above when onboarded.

3. **Validation & Error Handling**:
   - The panel should display proper validation messages for missing or invalid inputs.
   - Error handling should be consistent with the backend error responses.

4. **User Interface**:
   - The UI should display the expense categories and expenses in a user-friendly manner, allowing sorting and filtering where appropriate.

### Some examples how Expense can be created
```json
{
  "_id": "652f3dfc1c9f9b3b6d4e9875",
  "totalValue": {
    "object": "ExpenseValueDto",
    "amount": 1500,
    "currency": "USD"
  },
  "expensedAt": "2024-10-05T10:00:00.000Z",
  "description": "Monthly office supplies and salary payments",
  "items": [
    {
      "categories": [
        {
          "name": "ProductPurchase",
          "description": "Purchases of beauty and barber supplies like shampoos, conditioners, and tools"
        }
      ],
      "itemValue": {
        "amount": 300,
        "currency": "USD"
      },
      "description": "Purchased shampoos and conditioners"
    },
    {
      "categories": [
        {
          "name": "Salary",
          "description": "Expenses related to staff salaries and wages"
        }
      ],
      "itemValue": {
        "amount": 1000,
        "currency": "USD"
      },
      "description": "Salary payment for Jane Doe for September",
      "source": {
        "name": "Jane Doe",
        "sourceId": "5f7b1b3b1f4b1d001f1b1f4c", 
        "sourceType": "member"
      }
    },
    {
      "categories": [
        {
          "name": "Rent",
          "description": "Monthly rental payments for the salon space"
        }
      ],
      "itemValue": {
        "amount": 500,
        "currency": "USD"
      },
      "description": "Paid rent for October"
    }
  ]
},
{
  "_id": "652f3dfc1c9f9b3b6d4e9876",
  "totalValue": {
    "object": "ExpenseValueDto",
    "amount": 2000,
    "currency": "USD"
  },
  "expensedAt": "2024-09-30T10:00:00.000Z",
  "description": "End of month expenses",
  "items": [
    {
      "categories": [
        {
          "name": "Utilities",
          "description": "Expenses for electricity, water, gas, and internet"
        }
      ],
      "itemValue": {
        "amount": 300,
        "currency": "USD"
      },
      "description": "Electricity and water bill for September"
    },
    {
      "categories": [
        {
          "name": "Marketing",
          "description": "Advertising and marketing expenses such as social media ads and flyers"
        }
      ],
      "itemValue": {
        "amount": 500,
        "currency": "USD"
      },
      "description": "Paid for Facebook and Instagram ads"
    },
    {
      "categories": [
        {
          "name": "Equipment",
          "description": "Purchases or maintenance of equipment like clippers, scissors, and chairs"
        }
      ],
      "itemValue": {
        "amount": 1200,
        "currency": "USD"
      },
      "description": "Purchased new clippers and chairs"
    }
  ]
},
{
  "_id": "652f3dfc1c9f9b3b6d4e9877",
  "totalValue": {
    "object": "ExpenseValueDto",
    "amount": 1200,
    "currency": "USD"
  },
  "expensedAt": "2024-09-15T10:00:00.000Z",
  "description": "Mid-month staff and supplies",
  "items": [
    {
      "categories": [
        {
          "name": "Advance",
          "description": "Expenses related to staff advance"
        }
      ],
      "itemValue": {
        "amount": 800,
        "currency": "USD"
      },
      "description": "Advance payment for staff"
    },
    {
      "categories": [
        {
          "name": "Cleaning",
          "description": "Cleaning supplies and services to maintain the salon"
        }
      ],
      "itemValue": {
        "amount": 400,
        "currency": "USD"
      },
      "description": "Purchased cleaning supplies for the month"
    }
  ]
},
{
  "_id": "652f3dfc1c9f9b3b6d4e9878",
  "totalValue": {
    "object": "ExpenseValueDto",
    "amount": 2500,
    "currency": "USD"
  },
  "expensedAt": "2024-10-01T10:00:00.000Z",
  "description": "New month startup expenses",
  "items": [
    {
      "categories": [
        {
          "name": "Subscriptions",
          "description": "Software and service subscriptions like booking systems or management tools"
        }
      ],
      "itemValue": {
        "amount": 200,
        "currency": "USD"
      },
      "description": "Subscription for the booking management tool"
    },
    {
      "categories": [
        {
          "name": "Training",
          "description": "Costs for employee training and professional development"
        }
      ],
      "itemValue": {
        "amount": 2300,
        "currency": "USD"
      },
      "description": "Paid for professional development training for staff"
    }
  ]
},
{
  "_id": "652f3dfc1c9f9b3b6d4e9879",
  "totalValue": {
    "object": "ExpenseValueDto",
    "amount": 1800,
    "currency": "USD"
  },
  "expensedAt": "2024-09-20T10:00:00.000Z",
  "description": "Business operational costs",
  "items": [
    {
      "categories": [
        {
          "name": "Insurance",
          "description": "Business insurance and liability coverage"
        }
      ],
      "itemValue": {
        "amount": 1200,
        "currency": "USD"
      },
      "description": "Monthly business insurance premium"
    },
    {
      "categories": [
        {
          "name": "Licenses",
          "description": "Fees for business licenses and permits"
        }
      ],
      "itemValue": {
        "amount": 600,
        "currency": "USD"
      },
      "description": "Annual business license renewal"
    }
  ]
},
{
  "_id": "652f3dfc1c9f9b3b6d4e9880",
  "totalValue": {
    "object": "ExpenseValueDto",
    "amount": 3000,
    "currency": "USD"
  },
  "expensedAt": "2024-09-25T10:00:00.000Z",
  "description": "Miscellaneous expenses for the quarter",
  "items": [
    {
      "categories": [
        {
          "name": "Delivery",
          "description": "Expenses related to product deliveries"
        }
      ],
      "itemValue": {
        "amount": 800,
        "currency": "USD"
      },
      "description": "Delivery costs for the quarter"
    },
    {
      "categories": [
        {
          "name": "Other",
          "description": "Miscellaneous expenses not covered by other tags"
        }
      ],
      "itemValue": {
        "amount": 2200,
        "currency": "USD"
      },
      "description": "Miscellaneous office and salon expenses"
    }
  ]
}
```
### **Tasks**:

- [ ] Create UI components for managing expenses (CRUD operations).
- [ ] Create UI components for managing expense categories.
- [ ] Ensure default categories are set when a new business is onboarded.
- [ ] Test all endpoints with real data to ensure functionality.
